### ISSUE TITLE
Investigate performance

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/ex_libnice#16]
We've seen that CPU utilisation for the libnice C node is around 3-5% of a core on our test machine for WebRTC streaming. That's quite a lot as for passing packets through a socket.

**Comment by mickel8** [comment]
# Introduction

ExLibnice works as follows:

```                                                    
| Elixir code | < -- tcp connection -- > | C node | --- spawns --- > | gloop thread |
                                                           
```
## Commands

```sh
# -F - frequency of sampling - if not provided output file can be quite large
# -g - call-graph/stacktrace 
perf record -F 99 -p <PID> -g -- sleep 60

# read recorded data
perf report 

# record CPU and memory usage 
psrecord 2325964 --log 2325964_4 --duration 60 --interval 1
```

## Test environment
Membrane Sandbox machine:
* Intel Xeon Processor 2.3 GHz, 4 cores


## Scenario with one peer 
Data represents 60 seconds of running videoroom with one peer in the room.

#### Parent process

It is quite strange but it looks like the values of `Self` don't sum up to 100% but they should.

Anyway, we can see that we spend 35.82% (Children column) of the time in the `do_writev` function. `do_writev` function has `0.00%` self overhead which means that all the time we spend in functions that are called in `do_writev` (its children).
`do_writev` is resposible for sending messages over TCP so this is probably function used for communication between Elixir and C. In other words we can probably say that 1/3 of the time the parent process is spending on sending messages to the Elixir code.

```
    Children      Self  Command  Shared Object            Symbol  
+   70.90%     0.00%  native   ld-musl-x86_64.so.1      [.] 0x00007fdb4cf05352
+   69.40%     0.00%  native   [kernel.kallsyms]        [k] entry_SYSCALL_64_after_hwframe
+   68.66%     0.75%  native   [kernel.kallsyms]        [k] do_syscall_64
+   35.82%     0.00%  native   [kernel.kallsyms]        [k] __x64_sys_writev
-   35.82%     0.00%  native   [kernel.kallsyms]        [k] do_writev
   - do_writev
      - 35.07% vfs_writev
         - do_iter_write
            - 34.33% do_iter_readv_writev
               - sock_write_iter
                  - 33.58% sock_sendmsg
                     - inet_sendmsg
                       tcp_sendmsg
                     - tcp_sendmsg_locked
                        - 32.09% tcp_push
                             __tcp_push_pending_frames
                           + tcp_write_xmit
                        + 0.75% sk_stream_alloc_skb
                    0.75% security_socket_sendmsg
              0.75% fsnotify
        0.75% fput_many
```


It's quite hard to tell how much time we spend receiving from TCP socket.

```
-   34.33%     0.00%  native   [kernel.kallsyms]        [k] do_iter_readv_writev
     do_iter_readv_writev
   - sock_write_iter
      - 33.58% sock_sendmsg
         - inet_sendmsg
           tcp_sendmsg
         - tcp_sendmsg_locked
            - 32.09% tcp_push
                 __tcp_push_pending_frames
               - tcp_write_xmit
                  - 30.60% __tcp_transmit_skb
                       ip_queue_xmit
                     - __ip_queue_xmit
                        - 29.10% ip_local_out
                           - 21.64% ip_output
                              - 20.90% ip_finish_output
                                   __ip_finish_output
                                 - ip_finish_output2
                                    - 16.42% __local_bh_enable_ip
                                         do_softirq.part.0
                                         do_softirq_own_stack
                                         __softirqentry_text_start
                                         net_rx_action
                                         process_backlog
                                         __netif_receive_skb
                                       - __netif_receive_skb_one_core
                                          - 15.67% ip_rcv  <<<<<< ============= HERE ? ============= >>>>>
                                               ip_rcv_finish
                                               ip_local_deliver
                                               ip_local_deliver_finish
                                             - ip_protocol_deliver_rcu
                                                - tcp_v4_rcv
                                                  tcp_v4_do_rcv
                                                  tcp_rcv_established
                                                  tcp_data_ready
                                                - sock_def_readable
                                                   - __wake_up_sync_key
                                                     __wake_up_common_lock
                                                     __lock_text_start
                                            0.75% nf_hook_slow
                                    + 2.99% dev_queue_xmit
                                0.75% nf_hook_slow
                           + 6.72% __ip_local_out
                             0.75% ip_send_check
                        + 0.75% __sk_dst_check
                    0.75% tcp_options_write
            + 0.75% sk_stream_alloc_skb
        0.75% security_socket_sendmsg
 ```
 
We spend 15,67% in `ip_rcv` which then calls `tcp_v4_rcv` which probably is a function called when something arrives on TCP socket but I have no idea why `tcp_v4_rcv` is called by `tcp_sendmsg`?
 
 Assuming `ip_rcv` is responsible for receiving data then we spend ~50% on communication via TCP in the parent process. There might be also sam `poll` mechanism that also consumes some CPU but it's not taken to the computation as the parent process also receives UDP messages (I am not sure why. I would expect that child process would do this as it handles gloop).
 

The following figure shows CPU usage by main process depening on peers in the room.
 
![image](https://user-images.githubusercontent.com/24651552/127538170-caf23a9d-de4d-44fe-8985-54435b96813e.png)

We can see that the more peers are in the room the more CPU we use.
From 2-4% for one peer to 5-7% for four peers.
If our assumptions are correct i.e. at least 50% of the time main process spends sending and receivig messages to/from Elixir then removing this communication should speed up C node so that the CPU usage for 4 peers should be between 2.5-3.5% for one main process.


The following figure shows output from `htop`  during test for four peers 
![image](https://user-images.githubusercontent.com/24651552/127539657-ea4f2b9d-7f7c-40a0-8827-1772ceed7ffd.png)

Green color indicates that the process was spawned by the white one.


Results are attached in [parent_process.zip](https://github.com/membraneframework/ex_libnice/files/6902505/parent_process.zip)

`perf.data` can be read using `perf report` in directory in which `perf.data` is.

 #### Child process
 ##### TODO
 
# Possible solutions
* use shared memory instead of sending messages via TCP between Elixir and C
* move to NIF
* use TURN instead of ICE 
* implement ICE in Elixir

**Comment by mickel8** [comment]
# ExLibnice as NIF 

## Test environment:
Membrane Sandbox machine:
* Intel Xeon Processor 2.3 GHz, 4 cores
* muted microphone
* meassurements every 500ms

### 4 peers
![ex_libnice_nif_vs_cnode_4_peers](https://user-images.githubusercontent.com/24651552/128864009-b01e626e-a381-4656-bc39-df80cbf90ab7.png)

### 8 peers
![ex_libnice_nif_vs_cnode_8_peers](https://user-images.githubusercontent.com/24651552/128864014-59df8843-aa66-4876-bd44-cfc3208bb297.png)
